config/routes.rb
SocialCoverMaker::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  scope "(:locale)", :locale => /#{I18n.available_locales.join("|")}/ do
    root :to => 'home#index'

    match '/about' => 'home#about'
    match '/privacy_policy' => 'home#privacy_policy', :as => 'privacy_policy'
    match '/about_us' => 'home#about_us'
    match '/features' => 'home#features'
    match '/faq' => 'home#faq', :as => 'faq'
    match 'contact' => 'contact#new', :as => 'contact', :via => :get
    match 'contact' => 'contact#create', :as => 'contact', :via => :post
    match 'contact_success' => 'contact#contact_success', :via => :get
    match '/youtube_lightbox' => 'home#youtube_lightbox'

    get "blog_comments/index"
    resources :blog_comments do
      get 'n_comments', :on => :collection
    end

    controller :blog_entries, :only => [:index, :create] do
      match '/blog' => :index, :as => :blog ,:via => [:get]
      match '/blog/:slug' => :show, :as => :blog_entry, :via => [:get]
      match '/blog/tag/:slug' => :index_by_tag, :as => :blog_index_by_tag, :via => [:get]
      match '/blog/category/:slug' => :index_by_category, :as => :blog_index_by_category, :via => [:get]
    end

    resources :templates, :only => [:show, :index], :path => "themes" do
      post 'submit', :on => :collection
      post 'download', :on => :member
      get 'tab_comments', :on => :member
      get 'tab_items', :on => :member
      get 'tab_output', :on => :member
      get 'request_download_links', :on => :member
      get 'tab_similars', :on => :member
      get 'examples', :on => :member
      post 'submit_template_example', :on => :collection
    end

    resources :template_examples, :only => [:index]

    resources :template_comments, :only => [:index, :create] do
      get 'n_comments', :on => :collection
    end

    resources :images
    match '/images/:id/crop' => 'images#crop'

    resources :template_categories
    resources :blog_categories

    match "/404", :to => "errors#not_found"#adicionada para que a pagina 404 seja tratada pelo controlador
  end

end

app/models/blog_entry.rb
class BlogEntry < ActiveRecord::Base
  attr_accessible :html, :slug, :title, :excerpt, :blog_category_id #att adicionado a' mao
  validates :slug, :uniqueness => true, :presence => true
  belongs_to :blog_category
  has_many :tags, :through => :blog_entries_tags
  has_many :blog_entries_tags
  has_many :blog_comments

  after_create :make_slug

  def self.months
    ['january', 'february', 'march', 'april', 'may', 'june', 'july', 'august', 'september', 'october', 'november', 'december']
  end

  def self.posts_by_year
    posts_by_year = {}
    today = Date.today
    current_month = today.month
    current_year = today.year

    (2012..current_year).to_a.each do |year|
      posts_by_month = {}

      year == current_year ? max_month = (current_month-1) : max_month = 11##para acabar no mês actual
      (0..max_month).to_a.each do |i|
        start = DateTime.new(year,i+1,1)
        if (i+2) != 13
          finish = DateTime.new(year,i+2,1)
        else
          finish = DateTime.new(year+1,1,1)
        end
        posts_by_month[months[i]] = BlogEntry.where(:created_at => (start..finish))
      end
      posts_by_year[year.to_s] = posts_by_month
    end
    posts_by_year
  end

  def make_slug
     @slug = Utils.to_slug(self.title.dup, self)
     self.slug = @slug
     self.save
  end

end

app/controllers/blog_entries_controller.rb
class BlogEntriesController < ApplicationController
  before_filter :prepare_menu_data, :only => [:index, :show, :index_by_tag, :index_by_category]
  before_filter :is_blog_section
  before_filter :blog_entries_per_page, :only => [:index, :index_by_tag, :index_by_category]
  
  # GET /blog_entries
  # GET /blog_entries.json
  def index
    @blog_entries = BlogEntry.paginate(:per_page => blog_entries_per_page, :page => params[:page])
    
    @title = t('blog')


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @blog_entries }
    end
  end

  # GET /blog_entries/1
  # GET /blog_entries/1.json
  def show
    @blog_entry = BlogEntry.find_by_slug(params[:slug])
    
     
    @len = @blog_entry.tags.count
    @count = 0
    @comments_count = BlogComment.where(:blog_entry_id => @blog_entry.id, :approved => true).count
    @quantity = 2
    all_blog_entry_comments = @blog_entry.blog_comments
    @all_blog_entry_comments_size = all_blog_entry_comments.where(:approved=>true).size
    @blog_comments = all_blog_entry_comments.where(:approved=>true).limit(@quantity)
    @offset = 0
    @new_comment = BlogComment.new
    
    #for title and meta datas
    @title = @blog_entry.title
    @meta_keywords = BlogEntriesTag.get_tags_keywords(@blog_entry)
    @meta_description = @blog_entry.excerpt.truncate(200)
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @blog_entry }
    end
  end

  # GET /blog_entries/new
  # GET /blog_entries/new.json
  def new
    @blog_entry = BlogEntry.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @blog_entry }
    end
  end

  # GET /blog_entries/1/edit
  def edit
    @blog_entry = BlogEntry.find(params[:id])
  end

  # POST /blog_entries
  # POST /blog_entries.json
  def create
    @blog_entry = BlogEntry.new(params[:blog_entry])

    respond_to do |format|
      if @blog_entry.save
        format.html { redirect_to @blog_entry, notice: 'Blog entry was successfully created.' }
        format.json { render json: @blog_entry, status: :created, location: @blog_entry }
      else
        format.html { render action: "new" }
        format.json { render json: @blog_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /blog_entries/1
  # PUT /blog_entries/1.json
  def update
    @blog_entry = BlogEntry.find(params[:id])

    respond_to do |format|
      if @blog_entry.update_attributes(params[:blog_entry])
        format.html { redirect_to @blog_entry, notice: 'Blog entry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @blog_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blog_entries/1
  # DELETE /blog_entries/1.json
  def destroy
    @blog_entry = BlogEntry.find(params[:id])
    @blog_entry.destroy

    respond_to do |format|
      format.html { redirect_to blog_entries_url }
      format.json { head :no_content }
    end
  end

  def index_by_tag
    @blog_entries = []
    tag = Tag.where(:slug => params[:slug]).first
     @title = tag.name
    if tag
      BlogEntry.all.each do |be|
        if be.tags.include? tag
          @blog_entries << be
        end
      end
      @blog_entries = tag.blog_entries.paginate(:per_page => blog_entries_per_page, :page => params[:page])
    end

    render :index
  end

  def index_by_category
    @blog_entries = []
    category = BlogCategory.where(:slug => params[:slug]).first
     @title = category.name
    if category
      BlogEntry.all.each do |be|
        if be.blog_category.id == category.id
          @blog_entries << be
        end
      end
      @blog_entries = BlogEntry.where(:blog_category_id => category.id).paginate(:per_page => blog_entries_per_page, :page => params[:page])

    end

    render :index
  end

  private
    def prepare_menu_data
      @categories = BlogCategory.all
      @posts_by_year = BlogEntry.posts_by_year
    end
    
    #permite definir a secção blog como selecionada na barra superior
    def is_blog_section
      @is_blog_section = 1;
    end

  def blog_entries_per_page
    @blog_entries_per_page = 2
  end
end

app/helpers/blog_entries_helper.rb
module BlogEntriesHelper
end

app/views/blog_entries/_form.html.erb
<%= form_for(@blog_entry) do |f| %>
  <% if @blog_entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog_entry.errors.count, "error") %> prohibited this blog_entry from being saved:</h2>

      <ul>
      <% @blog_entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :html %><br />
    <%= f.text_field :html %>
  </div>
  <div class="field">
    <%= f.label :slug %><br />
    <%= f.text_field :slug %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blog_entries/_menu.html.haml
.blogmenu
  .menuItem
    .menuItemText.menuItemHomeIcon
      = link_to t('homeIndex'), blog_path
  .menuItem
    .menuItemText.menuItemCategoryIcon#menu_categories
      =t('categories')
  #menu_categories_submenu
    - @categories.each do |c|
      .submenuItem
        .submenuItemText
          = link_to c.name, blog_index_by_category_path(c.slug)
    
  .menuItem
    .menuItemText.menuItemCalendarIcon#menu_calendar
      =t('calendar')
  #menu_calendar_submenu
    - @posts_by_year.each do |py_k, py_v|
      - py_v.each do |pm_k, pm_v|
        .submenuItem
          .submenuItemText
            = pm_k + " " + py_k
          
        .div{:class => ("subsubmenuContainer" unless pm_v.empty?)}
          - pm_v.each do |post|
            .subsubmenuItem
              .subsubmenuItemText
                = link_to post.title, blog_entry_url(post.slug)
        
    
  .finalItem
    

app/views/blog_entries/edit.html.erb
<h1>Editing blog_entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog_entry %> |
<%= link_to 'Back', blog_entries_path %>

app/views/blog_entries/index.html.erb
<div class="blockSpace"></div>
  <div class="post">
    <% @blog_entries.each do |blog_entry| %>
    <div class="postHeader">
      <h1><%= link_to blog_entry.title, blog_entry_path(blog_entry.slug) %></h1>
      <strong><%= t('category') %>:</strong> 
      <%= link_to blog_entry.blog_category.name, blog_index_by_category_path(blog_entry.blog_category.slug) %>  | 
      <span class="comments">
      	<% @comments_count = BlogComment.where(:blog_entry_id => blog_entry.id, :approved => true).count%> 
      	<%= @comments_count.to_s %> 
      	<%if @comments_count != 0 %>
      		<%= link_to t('comments'), blog_entry_path(blog_entry.slug)+ '#comments', :id => "link_to_comments" %>
      	<%else%>
      		<%= t('comments') %>
      	<%end%>
      </span>
      <hr class="blogMinihrUp" />
      <hr class="blogMinihrDown" />
    </div>
    <div class="postContent hyphenate">
      <%= blog_entry.excerpt.html_safe %>
    </div>
    <div class="postfooter">
      <strong><%= t('date') %>:</strong> 
      <%= blog_entry.created_at.strftime('%b %d, %Y') %> |
      <strong>
      	<%= t('tag') %>:
      </strong> 
      <% @len = blog_entry.tags.count%>
      <% @count = 0 %>
      <% blog_entry.tags.each do |tag| %>
       	<% @count +=1 %>
        <%if @count != @len%>
       		<%= link_to tag.name + ', ', blog_index_by_tag_path(tag.slug) %>
       	<%else%>
       		<%= link_to tag.name, blog_index_by_tag_path(tag.slug) %>
       	<%end%>
      <% end %><div class="readMore">
        <%= link_to t('continueReading'), blog_entry_path(blog_entry.slug) %>
      </div>
      <div class="postfooterSombra">
        <span class="first"> </span>
        <span class="second"> </span>
        <span class="third"> </span>
      </div>
    </div>

    <% end %>
  
<%count = @blog_entries.count %>
<% if count > @blog_entries_per_page%>
  <%if params[:page] == '1' or !params[:page]%>
    <%p 'zzzzklndkjsbfdsçbfjdsbjfhbjdsb'%>
    <%= will_paginate @blog_entries, {:inner_window => 2, :outer_window => 0, :previous_label =>'<img alt="Icon-comment-blocked-previous" src="/assets/icons/icon-comment-blocked-previous.png"/>',:next_label =>'<img alt="Icon-comment-next" src="/assets/icons/icon-comment-next.png"/>'}%>
  <% end %>
  <% if params[:page].to_i > 1 and (params[:page].to_i * @blog_entries_per_page) <= count %>
    <%= will_paginate @blog_entries, {:inner_window => 2, :outer_window => 0, :previous_label =>'<img alt="Icon-comment-previous" src="/assets/icons/icon-comment-previous.png"/>',:next_label =>'<img alt="Icon-comment-next" src="/assets/icons/icon-comment-next.png"/>'}%>
  <% end %>
  <%if params[:page].to_i > 1 and (params[:page].to_i * @blog_entries_per_page) > count%>
    <%= will_paginate @templates, {:inner_window => 2, :outer_window => 0, :previous_label =>'<img alt="Icon-comment-previous" src="/assets/icons/icon-comment-previous.png"/>',:next_label =>'<img alt="Icon-comment-blocked-next" src="/assets/icons/icon-comment-blocked-next.png"/>'}%>
  <% end %>
<% end %>
</div>
<%= render 'menu' %>

app/views/blog_entries/new.html.erb
<h1>New blog_entry</h1>

<%= render 'form' %>

<%= link_to 'Back', blog_entries_path %>

app/views/blog_entries/show.html.erb
<div class="blockSpace"></div>
  
<div class="post">
  <div class="postHeader">
    <h1><%= @blog_entry.title %></h1>
    <strong><%= t('category') %>:</strong>
     <%= link_to @blog_entry.blog_category.name, blog_index_by_category_path(@blog_entry.blog_category.slug) %>  |  
     <span class="comments">
     	<%=  @comments_count %> 
     	<%-if @comments_count != 0 %>
     		<%=link_to t('comments'), '#comments', :id => "link_to_comments" %>
     	<%-else%>
     		<%= t('comments') %>
     	<%end%>
     </span>
    <hr class="blogMinihrUp" />
    <hr class="blogMinihrDown" />
  </div>
  <div class="postContent hyphenate">
    <%= @blog_entry.html.html_safe %>
  </div>
  <div class="postfooter">
    <strong>
    	<%= t('date') %>:
    </strong> 
    <%= @blog_entry.created_at.strftime('%b %d, %Y') %> | 
    <strong>
    	<%= t('tag') %>:
    </strong>
    <% @blog_entry.tags.each do |tag| %> 
    	<% @count +=1 %>
        <%if @count != @len%>
       	  <%= link_to tag.name + ', ', blog_index_by_tag_path(tag.slug) %>
       	<%else%>
          <%= link_to tag.name, blog_index_by_tag_path(tag.slug) %>
       	<%end%>
    <% end %>
    <div class="postfooterSombra">
      <span class="first"> </span>
      <span class="second"> </span>
      <span class="third"> </span>
    </div>
  </div>
  
  <%= render 'blog_comments/form' %>
  <%= render 'blog_comments/comments_excerpt' %>
    
</div>
<%= render 'menu' %>  