config/routes.rb
SocialCoverMaker::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  scope "(:locale)", :locale => /#{I18n.available_locales.join("|")}/ do
    root :to => 'home#index'

    match '/about' => 'home#about'
    match '/privacy_policy' => 'home#privacy_policy', :as => 'privacy_policy'
    match '/about_us' => 'home#about_us'
    match '/features' => 'home#features'
    match '/faq' => 'home#faq', :as => 'faq'
    match 'contact' => 'contact#new', :as => 'contact', :via => :get
    match 'contact' => 'contact#create', :as => 'contact', :via => :post
    match 'contact_success' => 'contact#contact_success', :via => :get
    match '/youtube_lightbox' => 'home#youtube_lightbox'

    get "blog_comments/index"
    resources :blog_comments do
      get 'n_comments', :on => :collection
    end

    controller :blog_entries, :only => [:index, :create] do
      match '/blog' => :index, :as => :blog ,:via => [:get]
      match '/blog/:slug' => :show, :as => :blog_entry, :via => [:get]
      match '/blog/tag/:slug' => :index_by_tag, :as => :blog_index_by_tag, :via => [:get]
      match '/blog/category/:slug' => :index_by_category, :as => :blog_index_by_category, :via => [:get]
    end

    resources :templates, :only => [:show, :index], :path => "themes" do
      post 'submit', :on => :collection
      post 'download', :on => :member
      get 'tab_comments', :on => :member
      get 'tab_items', :on => :member
      get 'tab_output', :on => :member
      get 'request_download_links', :on => :member
      get 'tab_similars', :on => :member
      get 'examples', :on => :member
      post 'submit_template_example', :on => :collection
    end

    resources :template_examples, :only => [:index]

    resources :template_comments, :only => [:index, :create] do
      get 'n_comments', :on => :collection
    end

    resources :images
    match '/images/:id/crop' => 'images#crop'

    resources :template_categories
    resources :blog_categories

    match "/404", :to => "errors#not_found"#adicionada para que a pagina 404 seja tratada pelo controlador
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include IENoMore

  before_filter :is_home_section, :only => [:index]
  before_filter :is_features_section, :only => [:features]
  before_filter :is_about_section, :only => [:about, :about_us, :contacts]
  before_filter :is_about_us_section, :only => [:about_us]
  before_filter :is_faq_section, :only => [:faq]

  def index
    @examples =  Template.get_top_six_templates
    print "\n\n\n\n---> " + @examples.size.to_s
    print "\n\n" + @examples.to_s
    @locale = params[:locale]
    @random_template = Template.get_random_template

    if !params[:locale]
      redirect_to root_path
    end
  end

  def about
    @title = t('about')
  end

  def about_us
    @title = t('team')
  end

  def contacts
    @title = t('contacts')
  end


  def privacy_policy
    @title = t('privacy_policy')
  end

  def features
    @title = t('features')
  end

  def youtube_lightbox
    @link = params[:link]
    render :layout => false
  end
  
  def faq
    
  end

  private
  
  #permite definir a secção página inicial como selecionada na barra superior
  def is_home_section
      @is_home_section = 1;
    end
  
  #permite definir a secção funcionalidades como selecionada na barra superior
  def is_features_section
    @is_features_section = 1;
  end
  
  #permite definir a secção about como selecionada na barra superior
  def is_about_section
    @is_about_section = 1;
  end
  
  def is_about_us_section
    @is_about_us_section = 1;
  end

  def is_ie6
    request.env["HTTP_USER_AGENT"] =~ /MSIE 6+?/
  end
  
  def is_faq_section
    @is_faq_section = 1;
  end

end

app/views/home/_about.en.html.haml
%h1= t('about')
%br
Improve your profile and surprise your friends!
%br
%br
Social Cover Maker is a website dedicated to customize
the profile of your favourite social networks, Facebook and Google+. 
This is a handy site and easy to use, allowing you to get
the best images to use on your cover and/or your profile. 
%br
%br
The Social Cover Maker is able to create the most impressive
combinations of images you can imagine, giving a new look to your personal page.
%br
%br
Browse the various topics and choose the one that most suits you. 
The themes available are organized into categories in order to easily find the ideal profile for you.
%br
%br
Try and share! ;)

app/views/home/_menu.html.haml
#staticCol
  %ul
    -if !@is_contact_section and !@is_about_us_section
      .active
        %li
          = link_to t('about'), about_path
    -else
      %li
        = link_to t('about'), about_path
    -if @is_about_us_section
      .active    
        %li 
          = link_to t('team'), about_us_path
    -else
      %li 
        = link_to t('team'), about_us_path
    -if @is_contact_section
      .active
        %li
          = link_to t('contact'), contact_path
    -else
      %li
        = link_to t('contact'), contact_path   

app/views/home/about.html.haml
#staticContentContainer
  .post
    .postContent
      = render 'about'
  = render 'menu'

app/views/home/about_us.html.haml
#staticContentContainer
  .post
    .postContent
      = render 'about_us'
  = render 'menu'

app/views/home/faq.en.html.haml
.faq_container#faq_top
  
  %h1 
    Frequently Asked Questions  

  .faq_questions  
    %ul
      %li
        - imagenotaccepted_q = 'One of my images is being rejected by Social Cover Maker. Why?'
        = link_to imagenotaccepted_q, '#imagenotaccepted_answer', :id => 'imagenotaccepted', :class => 'faqLink'
      %li
        - resize_q = 'My images are bigger (file size, not image dimension) than the maximum file size accepted by Social Cover Maker. How can i resize, reducing their size? (on Windows, Mac OS X, Ubuntu)?'
        = link_to resize_q, '#resize_answer', :id => 'resize', :class => 'faqLink'
      %li
        - uploadscm_q = 'How do i upload images to Social Cover Maker?'
        = link_to uploadscm_q, '#uploadscm_answer', :id => 'uploadscm', :class => 'faqLink'
      %li 
        - editoptions_q = 'How can i edit images after uploading them to Social Cover Maker?'
        = link_to editoptions_q, '#editoptions_answer', :id => 'editoptions', :class => 'faqLink'
      %li
        - uploadgplus_q = 'How can i upload the generated images to Google+?'
        = link_to uploadgplus_q, '#uploadgplus_answer', :id => 'uploadgplus', :class => 'faqLink'
        %li
          - reposition_q = 'Do i have to reposition the images after i upload them to Google+?'
          = link_to reposition_q, '#reposition_answer', :id => 'reposition', :class => 'faqLink'
      %li
        - imagerights_q = 'What happens to my images after uploading them to Social Cover Maker?'
        = link_to imagerights_q, '#imagerights_answer', :id => 'imagerights', :class => 'faqLink'
      %li
        - imagereutilization_q = 'Why can\'t i reuse the pictures i sent to Social Cover Maker, after opening other page?'
        = link_to imagereutilization_q, '#imagereutilization_answer', :id => 'imagereutilization', :class => 'faqLink'
      %li
        - wantothertemplate_q = 'The theme that i would like to apply to my images does not exist. What can i do?'
        = link_to wantothertemplate_q, '#wantothertemplate_answer', :id => 'wantothertemplate', :class => 'faqLink'
        
    %br
    %br
    %br
    
    
  .faq_questions_answers_container  
      
    #imagenotaccepted_answer.question_answer
      %h3
        =imagenotaccepted_q
        =link_to (image_tag("icons/icon_back_top.png", :alt => "top")), "#", :class => "link_to_faq_top"
      .answer
        %p
          At this moment, Social Cover Maker only accepts images on the following formats: 'JPG', 'JPEG' and 'PNG'; and images which size is lower or equal to 5 MB (MegaBytes). On this FAQ you can find help on how to change the format of your images, and how to reduce their size.
      
      
    #resize_answer.question_answer
      %h3
        = resize_q
        =link_to (image_tag("icons/icon_back_top.png", :alt => "top")), "#", :class => "link_to_faq_top"
      .answer
        %p
          We'll explain shorlty how to reduce image size on three of the most common operating systems:
        %h4
          Mac OS X (10.6 or later):
        %ol
          %li Right click on the image you want to resize;
          %li Select "Open with" and click on "Preview";
          %li Go to the top menu bar, and click on "Tools". Then click on "Adjust Size...";
          %li On the newly opened window, reduce the width/height of the image, until "Resulting Size" of the image, present on the bottom of this window, is lower or equal than 5MB;
          %li Press "Ok";
          %li Go back to the top menu bar, and click "File", then "Save As..." and save the file with a different name (so you won't lose the original image);
        %p
          If you still have doubts, check this tutorial on
          = succeed "," do
            = link_to "youtube", "http://youtu.be/HI-RFRnaXG4"
          or you can refer to the Apple's support page about 
          = succeed "." do
            = link_to "Preview", "http://support.apple.com/kb/HT2506?viewlocale=en_US"
        
        %h4
          Windows (Vista ou later):
        %ol
          %li Open Paint;
          %li Open the image you want to resize;
          %li On the tools that belong to the images group, click on "Resize";
          %li Reduce the Horizontal (width) or Vertical (height) value; 
          %li Click "Ok";
          %li Go back to the file menu, and click "Save As..." and save the file with a different name (so you won't lose the original image);
          %li Verify if the size is already lower or equal to 5MB.
        %p
          If you still have doubts, check this tutorial on
          = succeed "," do
            = link_to "youtube", "http://youtu.be/kETJzpEJeH4"
          or refer to the Windows support page on how to
          = succeed "." do
            = link_to 'resize a picture using Paint', 'http://windows.microsoft.com/en-GB/windows7/Resize-a-picture-using-Paint'
        %h4
          Ubuntu:
        %ol
          %li Open GIMP;
          %li Open the image you want to resize;
          %li On the top menu bar, select "Image", then click on "Scale Image...";
          %li Reduce the width/height of the image; 
          %li Click on "Scale" to apply;
          %li Go back to the top menu bar, and click "File", then "Save As..." and save the file with a different name (so you won't lose the original image);
          %li Verify if the size of the new image is already lower or equal to 5MB.
        %p
          If you still have doubts, check this tutorial on
          = succeed "." do
            = link_to "youtube", "http://youtu.be/2mpk-0eUhrk"
        
    #uploadscm_answer.question_answer
      %h3
        = uploadscm_q
        =link_to (image_tag("icons/icon_back_top.png", :alt => "top")), "#", :class => "link_to_faq_top"
      .answer
        %p
          On the
          = link_to "features", features_path
          page there are informations on how you can upload your images to our service, as well as an explaining video.
             
             
                
    #editoptions_answer.question_answer
      %h3
        = editoptions_q
        =link_to (image_tag("icons/icon_back_top.png", :alt => "top")), "#", :class => "link_to_faq_top"
      .answer
        %p
          After uploading an image, the edit button, next to the uploaded image preview, becomes active. If you press it, the edition window will open.
        %p
          Our service offers two ways of editing images, depending on the theme and the position of the images on the theme. On the most common way of editing the images, you have the possibility of selecting just a part of the image. You can move the current selection area, and you can increase/decrease the size of the selection area, by dragging it's corners. The image aspect ration is always the same and is immutable.
        .faq_crop_examples_container  
          .faq_crop_example  
            = image_tag 'faq/crop_ex1.png', :size => '200x180'
          .faq_crop_example
            = image_tag 'faq/crop_ex2.png', :size => '200x180'
          .faq_crop_example  
            = image_tag 'faq/crop_ex3.png', :size => '200x180'
        %p
          The second way of editing images (addressed in one of the explaining videos of the    
          = succeed ")" do
            = link_to 'features', features_path
          page, is normally used on the themes where from one image, the service generates both the cover and profile photos. On this type of edit, you can zoom in or out on the image using the buttons on the bottom right corner ('+' and '-'). You can also move the image by clicking on it and dragging around, if the resolution of the image allows it.
        .faq_crop_examples_container  
          .faq_crop_example_jwindow 
            = image_tag 'faq/crop2_ex1.png', :size => '300x120'
          .faq_crop_example_jwindow  
            = image_tag 'faq/crop2_ex3.png', :size => '300x120'
      


    #uploadgplus_answer.question_answer
      %h3
        = uploadgplus_q
        =link_to (image_tag("icons/icon_back_top.png", :alt => "top")), "#", :class => "link_to_faq_top"
      .answer
        %p
          On the
          = link_to "features", features_path
          page there is a video that explains the whole process. In the event of not being thorough enough, following, a more detailed explanation is given.
        %p
          After generating your new cover or profile, it is time to upload them to Google+. To send a profile photo you have to:
        %ol
          %li Login on your Google+ profile;
          %li Hover the mouse on your profile photo and click on "Change profile photo";
          %li Select the profile photo generated by our service;    
          %li A new window will be opened, where you can edit your photo. It is very important that you do nothing in this window, and just click on "Set as profile photo";
      
        %p  
          To send your cover photo:
          %ol
            %li Login on your Google+ profile;
            %li Hover the mouse on your cover photo and click on "Change cover photo";
            %li  Select the cover photo generated by our service;
        
        
    #reposition_answer.question_answer
      %h3
        = reposition_q
        =link_to (image_tag("icons/icon_back_top.png", :alt => "top")), "#", :class => "link_to_faq_top"
      .answer
        %p
          After uploading photos to Google+ generated by our service you can not reposition/rotate/cut the images, because you will be destroying the effect intended by the use of the theme. Just accept the default position and selection after you upload it.
      
      
      
    #imagerights_answer.question_answer
      %h3
        = imagerights_q
        =link_to (image_tag("icons/icon_back_top.png", :alt => "top")), "#", :class => "link_to_faq_top"
      .answer
        %p
          All the images that you send to our service, as well as the ones that are generated from them, are eliminated from our server after 30 minutes. For more information refer to our
          = succeed " page." do
            =link_to "Privacy Police", privacy_policy_path
        
      
      
      
    #imagereutilization_answer.question_answer
      %h3
        = imagereutilization_q
        =link_to (image_tag("icons/icon_back_top.png", :alt => "top")), "#", :class => "link_to_faq_top"
      .answer  
        %p
          While the images you sent are still available on our server, it would be normal for you to reuse them. This functionality is not yet available, but will be on a later version of our service.  
      
      
      
    #wantothertemplate_answer.question_answer
      %h3
        = wantothertemplate_q
        =link_to (image_tag("icons/icon_back_top.png", :alt => "top")), "#", :class => "link_to_faq_top"
      .answer  
        %p
          If you thought of any theme that you would like us to add to the ones available at the moment, please
          = succeed ", explaining your idea!" do
            = link_to 'contact us', contact_path

app/views/home/faq.pt.html.haml
.faq_container#faq_top

  %h1 
    Frequently Asked Questions  

  .faq_questions  
    %ul
      %li
        - imagenotaccepted_q = 'Uma das minhas imagens não é aceite pelo Social Cover Maker. Porquê?'
        = link_to imagenotaccepted_q, '#imagenotaccepted_answer', :id => 'imagenotaccepted', :class => 'faqLink'
      %li
        - resize_q = 'As minhas imagens são maiores (tamanho do ficheiro) do que o Social Cover Maker me permite enviar. Como faço para reduzir o tamanho das minhas imagens (em Windows, Mac OS X, Ubuntu)?'
        = link_to resize_q, '#resize_answer', :id => 'resize', :class => 'faqLink'
      %li
        - uploadscm_q = 'Como faço upload de imagens para serem tratadas pelo Social Cover Maker?'
        = link_to uploadscm_q, '#uploadscm_answer', :id => 'uploadscm', :class => 'faqLink'
      %li 
        - editoptions_q = 'Como posso editar as imagens depois de fazer upload?'
        = link_to editoptions_q, '#editoptions_answer', :id => 'editoptions', :class => 'faqLink'
      %li
        - uploadgplus_q = 'Como faço upload das imagens geradas para o Google+?'
        = link_to uploadgplus_q, '#uploadgplus_answer', :id => 'uploadgplus', :class => 'faqLink'
        %li
          - reposition_q = 'Preciso de posicionar as imagens depois de fazer upload para o Google+?'
          = link_to reposition_q, '#reposition_answer', :id => 'reposition', :class => 'faqLink'
      %li
        - imagerights_q = 'O que acontece às minhas imagens depois de fazer upload para o SCM?'
        = link_to imagerights_q, '#imagerights_answer', :id => 'imagerights', :class => 'faqLink'
      %li
        - imagereutilization_q = 'Porque não posso reutilizar as imagens que enviei para o SCM, depois de mudar de página?'
        = link_to imagereutilization_q, '#imagereutilization_answer', :id => 'imagereutilization', :class => 'faqLink'
      %li
        - wantothertemplate_q = 'O tema que eu gostava de aplicar às minhas fotos não existe. O que posso fazer?'
        = link_to wantothertemplate_q, '#wantothertemplate_answer', :id => 'wantothertemplate', :class => 'faqLink'
        
    %br
    %br
    %br
    
    
  .faq_questions_answers_container  
      
    #imagenotaccepted_answer.question_answer
      %h3
        =imagenotaccepted_q
        =link_to (image_tag("icons/icon_back_top.png", :alt => "topo")), "#", :class => "link_to_faq_top"
      .answer
        %p
          Neste momento o Social Cover Maker apenas aceita imagens nos seguintes formatos: 'JPG', 'JPEG' e 'PNG'; e imagens que ocupem 5 MB (MegaBytes) ou menos. Ainda nesta FAQ pode encontrar ajuda para alterar o formato das suas imagens e para reduzir o tamanho das mesmas.  
      
      
    #resize_answer.question_answer
      %h3
        = resize_q
        =link_to (image_tag("icons/icon_back_top.png", :alt => "topo")), "#", :class => "link_to_faq_top"
      .answer
        %p
          Vamos explicar sucintamente como pode reduzir o tamanho das suas imagens em três dos sistemas operativos mais comuns:
        %h4   
          Mac OS X (10.6 ou posterior):
        %ol
          %li Clicar com o botão direito do rato em cima da imagem que pretende redimensionar;
          %li Seleccione "Abrir Com" e depois clique em "Pré-Visualização";
          %li Vá até à barra de menu, no topo do ecrã, e clique em "Ferramentas" e depois em "Ajustar Tamanho...";
          %li Na nova janela, diminua a altura/largura da imagem, até ao "Tamanho Resultante" da imagem, apresentado no fundo dessa janela, ser inferior a 5MB;
          %li Volte à barra de menu, no topo do ecrã, clique em "Ficheiro" e depois em "Guardar como...", e guarde a imagem com outro nome (de modo a não perder a imagem original);
        %p
          Se continuar com dúvidas, pode consultar este tutorial no 
          = succeed "," do
            = link_to "youtube", "http://youtu.be/OMMnT8MWvms"
          ou consultar a página de suporte da Apple sobre a aplicação
          = succeed "." do
            = link_to "Pré-visualização", "http://support.apple.com/kb/HT2506?viewlocale=pt_BR"
        %h4
          Windows (Vista ou posterior):
        %ol
          %li Abrir o Paint;
          %li Abrir a imagem que pretende redimensionar;
          %li Nas ferramentas pertencentes ao grupo das imagens, clique em "Redimensionar";
          %li Diminua o valor Horizontal (largura) ou Vertical (altura); 
          %li Guarde a imagem com outro nome (de modo a não perder a imagem original);
          %li Verifique se já tem menos de 5MB.
        %p
          Se continuar com dúvidas, pode consultar este tutorial no 
          = link_to "youtube", "http://youtu.be/c_VLaTWcKG0"
          , ou consultar a página de suporte do Windows sobre como 
          = succeed "." do
            = link_to "redimensionar uma imagem usando o Paint", "http://windows.microsoft.com/pt-BR/windows7/Resize-a-picture-using-Paint"
        %h4
          Ubuntu:
        %ol
          %li Abrir o GIMP;
          %li Já no GIMP, abrir a imagem que pretende redimensionar;
          %li Na barra de menu superior, seleccionar "Imagem" e depois clicar em "Escalar Imagem...";
          %li Editar a altura/largura da imagem; 
          %li Clicar em Escala para aplicar as alterações;
          %li Voltar à barra de menu, clicar em "Ficheiro" e depois em "Guardar como...", e guardar a imagem com outro nome (de modo a não perder a imagem original);
          %li Verificar se o tamanho da imagem já é inferior a 5MB.
        %p
          Se continuar com dúvidas, pode consultar este tutorial no 
          = succeed "." do
            = link_to "youtube", "http://youtu.be/GsC-G3kAZsY"
        
    #uploadscm_answer.question_answer
      %h3
        = uploadscm_q
        =link_to (image_tag("icons/icon_back_top.png", :alt => "topo")), "#", :class => "link_to_faq_top"
      .answer
        %p
          Na página das
          = link_to "funcionalidades", features_path
          tem informações sobre como fazer upload das imagens para o nosso serviço, assim como um vídeo explicativo.
             
             
                
    #editoptions_answer.question_answer
      %h3
        = editoptions_q
        =link_to (image_tag("icons/icon_back_top.png", :alt => "topo")), "#", :class => "link_to_faq_top"
      .answer
        %p
          Depois de fazer upload de uma imagem, o botão editar, junto à pré-visualização da imagem enviada, passa a estar disponível. Se clicar nesse botão, a janela de edição será aberta.
        %p
          O nosso serviço disponibiliza duas forma de edição de imagem, consoante o tema e a posição das imagem no tema. Na forma mais comum de edição, tem a possibilidade de seleccionar apenas uma parte da imagem. Pode mover toda a selecção, ou pode aumentar/diminuir o tamanho da selecção arrastando um dos extremos da mesma. A proporção da imagem, ou seja, a relação entre a largura e a altura da imagem é constante e imutável.
        .faq_crop_examples_container  
          .faq_crop_example  
            = image_tag 'faq/crop_ex1.png', :size => '200x180'
          .faq_crop_example
            = image_tag 'faq/crop_ex2.png', :size => '200x180'
          .faq_crop_example  
            = image_tag 'faq/crop_ex3.png', :size => '200x180'
        %p
          A segunda forma de edição de imagens (abordada no video explicativo presente na página
          = succeed ")," do
            = link_to 'funcionalidades', features_path
          normalmente é usada nos temas em que a partir de uma foto são geradas ambas as fotografias de capa e de perfil. Neste tipo de edição, pode aproximar ou afastar a imagem utilizando os botões no canto inferior direito ('+' e '-'). Pode também mover a imagem, clicando nela e arrastando, caso a resolução da mesma seja suficiente.
        .faq_crop_examples_container  
          .faq_crop_example_jwindow 
            = image_tag 'faq/crop2_ex1.png', :size => '300x120'
          .faq_crop_example_jwindow  
            = image_tag 'faq/crop2_ex3.png', :size => '300x120'
      


    #uploadgplus_answer.question_answer
      %h3
        = uploadgplus_q
        =link_to (image_tag("icons/icon_back_top.png", :alt => "topo")), "#", :class => "link_to_faq_top"
      .answer
        %p
          Na página das
          = link_to "funcionalidades", features_path
          existe um vídeo com a explicação de todo o processo. Para o caso de não ser suficiente, em seguida é apresentada uma explicação mais pormenorizada.
        %p
          Depois de gerado a sua nova capa ou perfil, chegou a altura de a enviar para o Google+. Para enviar a sua foto de perfil tem de:
        %ol
          %li Fazer login no seu perfil do Google+;
          %li Passar o rato por cima da sua foto de perfil, e clicar em cima do link "Alterar fotografia do perfil";
          %li Seleccionar a fotografia de perfil gerada, e clicar no botão "Definir como fotografia do perfil";
          %li Vai aparecer uma nova janela, onde pode editar a sua foto. É muito importante que não altere a pré-selecção, e apenas clique em "Definir como fotografia do perfil".
      
        %p  
          Para enviar a sua foto de capa tem de:
        %ol
          %li Fazer login no seu perfil do Google+;
          %li Passar o rato por cima da sua foto de capa, e clicar em cima do link "Alterar fotografia de capa";
          %li Seleccionar a fotografia de capa gerada pelo nosso serviço;
        
        
    #reposition_answer.question_answer
      %h3
        = reposition_q
        =link_to (image_tag("icons/icon_back_top.png", :alt => "topo")), "#", :class => "link_to_faq_top"
      .answer
        %p
          Depois de fazer upload das fotos geradas pelo nosso serviço para o Google+, não PODE reposicionar/rodar/cortar as imagens, porque ao fazê-lo, estará a estragar o efeito que se pretendia atingir com o tema.
      
      
      
      
    #imagerights_answer.question_answer
      %h3
        = imagerights_q
        =link_to (image_tag("icons/icon_back_top.png", :alt => "topo")), "#", :class => "link_to_faq_top"
      .answer
        %p
          Todas as imagens que envia para o nosso serviço, assim como as que são geradas a partir delas, são eliminadas do nosso servidor no prazo de 30 minutos. Para mais informações consulte a nossa página de 
          = succeed "." do
            =link_to "Política de Privacidade", privacy_policy_path
      
      
      
      
    #imagereutilization_answer.question_answer
      %h3
        = imagereutilization_q
        =link_to (image_tag("icons/icon_back_top.png", :alt => "topo")), "#", :class => "link_to_faq_top"
      .answer  
        %p
          Enquanto as imagens que enviou para o nosso servidor estiverem disponíveis, faz todo o sentido que possa voltar a utilizá-las, sem ter de as enviar novamente. Esta funcionalidade estará presente numa próxima versão do nosso serviço.
      
      
      
      
      
    #wantothertemplate_answer.question_answer
      %h3
        = wantothertemplate_q
        =link_to (image_tag("icons/icon_back_top.png", :alt => "topo")), "#", :class => "link_to_faq_top"
      .answer  
        %p
          Se pensou em algum tema que gostaria que nós disponibilizássemos, por favor
          = succeed ", explicando a sua ideia!" do
            = link_to 'contacte-nos', contact_path
      

app/views/home/youtube_lightbox.html.haml
%object{:height => "315", :width => "560"}
  %param{:name => "movie", :value => "#{@link}"}
  %param{:name => "allowFullScreen", :value => "true"}
  %param{:name => "allowscriptaccess", :value => "always"}
  %embed{:allowfullscreen => "true", :allowscriptaccess => "always", :height => "315", :src => "#{@link}", :type => "application/x-shockwave-flash", :width => "560"}