config/routes.rb
SocialCoverMaker::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  scope "(:locale)", :locale => /#{I18n.available_locales.join("|")}/ do
    root :to => 'home#index'

    match '/about' => 'home#about'
    match '/privacy_policy' => 'home#privacy_policy', :as => 'privacy_policy'
    match '/about_us' => 'home#about_us'
    match '/features' => 'home#features'
    match '/faq' => 'home#faq', :as => 'faq'
    match 'contact' => 'contact#new', :as => 'contact', :via => :get
    match 'contact' => 'contact#create', :as => 'contact', :via => :post
    match 'contact_success' => 'contact#contact_success', :via => :get
    match '/youtube_lightbox' => 'home#youtube_lightbox'

    get "blog_comments/index"
    resources :blog_comments do
      get 'n_comments', :on => :collection
    end

    controller :blog_entries, :only => [:index, :create] do
      match '/blog' => :index, :as => :blog ,:via => [:get]
      match '/blog/:slug' => :show, :as => :blog_entry, :via => [:get]
      match '/blog/tag/:slug' => :index_by_tag, :as => :blog_index_by_tag, :via => [:get]
      match '/blog/category/:slug' => :index_by_category, :as => :blog_index_by_category, :via => [:get]
    end

    resources :templates, :only => [:show, :index], :path => "themes" do
      post 'submit', :on => :collection
      post 'download', :on => :member
      get 'tab_comments', :on => :member
      get 'tab_items', :on => :member
      get 'tab_output', :on => :member
      get 'request_download_links', :on => :member
      get 'tab_similars', :on => :member
      get 'examples', :on => :member
      post 'submit_template_example', :on => :collection
    end

    resources :template_examples, :only => [:index]

    resources :template_comments, :only => [:index, :create] do
      get 'n_comments', :on => :collection
    end

    resources :images
    match '/images/:id/crop' => 'images#crop'

    resources :template_categories
    resources :blog_categories

    match "/404", :to => "errors#not_found"#adicionada para que a pagina 404 seja tratada pelo controlador
  end

end

app/models/template_comment.rb
class TemplateComment < ActiveRecord::Base
  before_create :user_is_well_known
  belongs_to :template
  attr_accessible :comment, :email, :name, :website, :approved, :template_id
  
  validates :comment, :presence => true
  
  validates :email,
            :presence => true,
            :format => { :with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i }
  validates :name, :presence => true
  
  #only auto approve comments for users with at least 5 Template Comments
  def user_is_well_known
    user_posts = TemplateComment.where(:email=>self.email, :name=>self.name, :approved => true)
    if user_posts.size >= 5
      self.approved = true
    end
  end
end

app/controllers/template_comments_controller.rb
class TemplateCommentsController < ApplicationController
  before_filter :is_templates_section, :only => [:index]
  def index
    @template = Template.find_by_slug(params[:slug])
    @template_comments = @template.template_comments.where(:approved => true)
  end

  def n_comments
    @quantity = 2
    @template = Template.find(params[:template_id])
    all_template_comments = @template.template_comments
    @all_template_comments_size = all_template_comments.where(:approved=>true).size
    @template_comments = all_template_comments.where(:approved=>true).limit(@quantity).offset(params[:offset].to_i)
    @offset = params[:offset].to_i

    render 'n_comments.js.erb'
  end

  def create
    @template_comment = TemplateComment.new(params[:template_comment])
    @saved = false
    @saved =  @template_comment.save

    respond_to do | format |
      format.js {render :layout => false}
    end
  end

  def is_templates_section
    @is_templates_section = 1;
  end
end

app/helpers/template_comments_helper.rb
module TemplateCommentsHelper
end

app/views/template_comments/_comments_excerpt.html.haml
%div{:id => "commentsBlock"}
  %div{:id => "comments",:class => "commentsContent"}
    
    -if @template_comments.size > 0
    
      - @template_comments.each do |template_comment|
        %div{:class => "comment"}
          = template_comment.comment
      
          %div{:class => "commentAuthor"}
            = template_comment.name + ","
            = template_comment.created_at.strftime('%b %d, %Y')
        %hr{:class => "blogMinihrUp"}
        %hr{:class => "blogMinihrDown"}
      
      -if @all_template_comments_size > 0
        -if (@offset + @quantity) < @all_template_comments_size
          %p
            = link_to t('next_comments'), n_comments_template_comments_path(:template_id => @template.id, :offset => (@offset + @quantity)), :remote => true

        -if @offset >0
          %p  
            = link_to t('previous_comments'), n_comments_template_comments_path(:template_id => @template.id, :offset => (@offset - @quantity) ), :remote => true
  
        .commentsFooter     
          =link_to t('see_all_comments'), template_comments_path(:slug => @template.slug)
          
    - else
      = t('first_to_comment')

app/views/template_comments/_form.html.haml
.div{:id => "comment_form", :class => "commentingdiv"}
  =form_for @new_comment, :remote => true do |f|
    .div{:class => "commentCenter"}
      = f.text_area :comment, :class => "commenttextareainput",:placeholder => t('leave_comment')
      .div{:class => "commentingfields"}
        .div{:class => "commentingfield"}
          =f.text_field :name, :placeholder => t('leave_name'), :class => "commenttextinput"
        .div{:class => "commentingfield"}
          =f.text_field :email, :placeholder => t('leave_email'), :class => "commenttextinput"
        .div{:class => "commentingfield"}
          =f.text_field :website, :placeholder => t('leave_website'), :class => "commenttextinput"
        =f.hidden_field :template_id, :value=>@template.id
        =f.submit t('submit'), :class => "commentbutton"
.div{:id => "submit_comment_result", :class => "commentingdiv"}

app/views/template_comments/create.js.erb
<% if @saved %>
  $('#comment_form').hide();
  <% if @template_comment.approved == true %>
    $( "#submit_comment_result" ).html( "<%= t('comment_approved') %> ");
  <% else %>
    $( "#submit_comment_result" ).html( "<%= t('comment_waiting_approval') %> ");
  <% end %>
  $('#submit_comment_result').show();
  
<% else %>
  $( "#submit_comment_result" ).html( "<% @template_comment.errors.messages.each do |k,v| %><p> <b><%=  BlogComment.human_attribute_name(k) + " " %></b> <%= v.first %></p><% end %>" );

  $('#submit_comment_result').show();

<% end %>

app/views/template_comments/index.html.haml
%h1= t('comments')
%br
%div{:id => "commentsBlock"}
  %div{:id => "comments",:class => "commentsContent"}
    - @template_comments.each do |template_comment|
      %div{:class => "comment"}
        = template_comment.comment
        %div{:class => "commentAuthor"}
          = template_comment.name + ","
          = template_comment.created_at.strftime('%b %d, %Y')
      %hr{:class => "blogMinihrUp"}
      %hr{:class => "blogMinihrDown"}
      
    
    .commentsFooter
      = link_to t('back'), template_path(@template.slug)      

app/views/template_comments/n_comments.js.erb
$( "#commentsBlock" ).replaceWith( "<%= escape_javascript( render( :partial => "comments_excerpt" ) ) %>" );