config/routes.rb
SocialCoverMaker::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  scope "(:locale)", :locale => /#{I18n.available_locales.join("|")}/ do
    root :to => 'home#index'

    match '/about' => 'home#about'
    match '/privacy_policy' => 'home#privacy_policy', :as => 'privacy_policy'
    match '/about_us' => 'home#about_us'
    match '/features' => 'home#features'
    match '/faq' => 'home#faq', :as => 'faq'
    match 'contact' => 'contact#new', :as => 'contact', :via => :get
    match 'contact' => 'contact#create', :as => 'contact', :via => :post
    match 'contact_success' => 'contact#contact_success', :via => :get
    match '/youtube_lightbox' => 'home#youtube_lightbox'

    get "blog_comments/index"
    resources :blog_comments do
      get 'n_comments', :on => :collection
    end

    controller :blog_entries, :only => [:index, :create] do
      match '/blog' => :index, :as => :blog ,:via => [:get]
      match '/blog/:slug' => :show, :as => :blog_entry, :via => [:get]
      match '/blog/tag/:slug' => :index_by_tag, :as => :blog_index_by_tag, :via => [:get]
      match '/blog/category/:slug' => :index_by_category, :as => :blog_index_by_category, :via => [:get]
    end

    resources :templates, :only => [:show, :index], :path => "themes" do
      post 'submit', :on => :collection
      post 'download', :on => :member
      get 'tab_comments', :on => :member
      get 'tab_items', :on => :member
      get 'tab_output', :on => :member
      get 'request_download_links', :on => :member
      get 'tab_similars', :on => :member
      get 'examples', :on => :member
      post 'submit_template_example', :on => :collection
    end

    resources :template_examples, :only => [:index]

    resources :template_comments, :only => [:index, :create] do
      get 'n_comments', :on => :collection
    end

    resources :images
    match '/images/:id/crop' => 'images#crop'

    resources :template_categories
    resources :blog_categories

    match "/404", :to => "errors#not_found"#adicionada para que a pagina 404 seja tratada pelo controlador
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='en'>
	<head>
		<title><%= title %></title>
		<meta name="keywords" content="<%= @meta_keywords%>" />
		<meta name="description" content="<%= @meta_description%>" />
		<meta itemprop="image" content="/assets/miniatura.png">
		<link rel="icon" href="/assets/favicon.png" type="image/x-icon"  />

    
		<%= stylesheet_link_tag    "application", :media => "all" %>
		<%= javascript_include_tag "application" %>
		
		
		<!--[if lt IE 9]>
	    	<%= stylesheet_link_tag "/ie/ie9", :media => "all" %>
	    	<%= javascript_include_tag "ie/jquery.placeholder.min" %>
  			<%= javascript_include_tag "ie/placeholder" %>
	    <![endif]-->

		<%= csrf_meta_tags %>
	
		
		<script type="text/javascript">
    
    jQuery(function () {
        
        var msie6 = jQuery.browser == 'msie' && jQuery.browser.version < 7;
        if (!msie6 && jQuery('#top-nav').length != 0) {
          
            var top = jQuery('#top-nav').offset().top - parseFloat(jQuery('#top-nav').css('margin-top').replace(/auto/, 0));
    
            jQuery(window).scroll(function (event) {
                
                // what the y position of the scroll is
    
                var y = jQuery(this).scrollTop();
    // whether that's below the form
                if (y >= top) {
                    // if so, ad the fixed class
                    jQuery('#top-nav').addClass('fixed');
                    jQuery('#top-bar').hide();
                    jQuery('#top-nav-logo').show('fast');
                } else {
                    // otherwise remove it
                    jQuery('#top-nav').removeClass('fixed');
                    jQuery('#top-bar').show();
                    jQuery('#top-nav-logo').hide('fast');
                }
            });
        }
    });
    </script>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-35167323-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
	</head>
	<body>
		<div id="header">
			<div id="top-bar" class="top-bar center">
				<h1 id="logo">
				  <a href=<%= root_path %> ><img src="/assets/social-cover-maker-logo.png" width="87" height="40" alt="SocialCoverMaker logo">
				    <h1 class="social-inline-block">Social Cover Maker</h1>
				  </a>
				</h1>
				<div id="follow_buttons_container"> 
				  
            <%= render 'social/follow_buttons' %>
          
        </div>
				<div id="action-instructions-container" style="">
					<div class="action-instructions">
						<ul class="example1">
							<li><%=link_to t('howto_linha1'), features_path %></li>
					        <li><%=link_to t('howto_linha2'), features_path %></li>
					        <li><%=link_to t('howto_linha3'), features_path %></li>
					        <li><%=link_to t('howto_linha4'), features_path %></li>
					        <li><%=link_to t('howto_linha5'), features_path %></li>
					    </ul>
					</div>
				</div>
			</div>
			<div id="top-nav" class="nav-wrapper" style="">
				<div id="nav-limits">
					
				<div id="nav">
					<ul>
					  <li id="top-nav-logo">
					    <%= link_to (image_tag "/assets/social-cover-maker-logo-blackWhite.png", :size =>"82x40", :alt =>"SocialCoverMaker logo") , root_path %>
            </li>
						<li>
						  <% if @is_home_section%>		
						  	<%= link_to t('home_page'), root_path, :id => 'home-link', :class=>"nav-active", :role=>'button', :tabindex=>'0' %>
						  <%else%>
						  	<%= link_to t('home_page'), root_path, :id => 'home-link', :role=>'button', :tabindex=>'0' %>
						  <%end%>	
						</li>
						<li>
							<% if @is_templates_section %>
								<%= link_to t('templates'), templates_path, :id => 'templates-link', :class=>"nav-active", :role=>'button', :tabindex=>'0' %>
							<% else%>
								<%= link_to t('templates'), templates_path, :id => 'templates-link', :role=>'button', :tabindex=>'0' %>
							<% end%>
						</li>
						<li>
							<%if @is_features_section%>
								<%= link_to t('features'), features_path, :id => 'features-link', :class=>"nav-active", :role=>'button', :tabindex=>'0' %>
							<%else%>
								<%= link_to t('features'), features_path, :id => 'features-link', :role=>'button', :tabindex=>'0' %>
							<%end%>
						</li>
						<li>
							<%if  @is_blog_section%>
								<%= link_to t('blog'), blog_path, :id => 'blog-link', :class=>"nav-active", :role=>'button', :tabindex=>'0' %>
							<%else%>
								<%= link_to t('blog'), blog_path, :id => 'blog-link', :role=>'button', :tabindex=>'0' %>
							<%end%>
						</li>
						<li>
							<% if @is_about_section%>
						  		<%= link_to t('about'), about_path, :id => 'about-link', :class=>"nav-active", :role=>'button', :tabindex=>'0' %>
							<%else%>
						  		<%= link_to t('about'), about_path, :id => 'about-link', :role=>'button', :tabindex=>'0' %>
							<%end%>
						</li>
						<li>
  						<% if @is_faq_section %>
  					  		<%= link_to t('faq'), faq_path, :id => 'faq-link', :class=>"nav-active", :role=>'button', :tabindex=>'0' %>
  						<%else%>
  					  		<%= link_to t('faq'), faq_path, :id => 'faq-link', :role=>'button', :tabindex=>'0' %>
  						<%end%>
  					</li>
					</ul>
				</div>
				
				</div>
			</div>
		</div>
		
	<div id="home">
		<%= yield %>
	<div id="footer">
			<hr />
			<div class="footLinks">
				<%= link_to t('contact'), contact_path %></a> 
				|
				<%= link_to t('privacy_policy'), privacy_policy_path %>
				|
				
				  <%= t('language')%>
          <%= select_tag(:select_locale, options_for_select( @options, @default ) ) %>
          
			</div>
			<div class="footAuthers">
				©
				2012        , <%= link_to "Social Cover Maker", root_path, :title => "Social Cover Maker" %>
				|  Powered by Claudio Novais, Daniel Oliveira, Pedro Silva.
			</div>
  </div>
		</div>
	</body>
</html>